region: eu-west-2

function_name: seoulian-user-api
handler: service.handler
description: User CRUD Operator
runtime: python3.8
role: service-role/seoulian-user-api-role-2nl3eeut

# S3 upload requires appropriate role with s3:PutObject permission
# (ex. basic_s3_upload), a destination bucket, and the key prefix
# bucket_name: 'example-bucket'
# s3_key_prefix: 'path/to/file/'

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
timeout: 3
memory_size: 128
#concurrency: 1
#

# If `tags` is uncommented then tags will be set at creation or update
# time.  During an update all other tags will be removed except the tags
# listed here.
#tags:
#    tag_1: foo
#    tag_2: bar

# Build options
build:
  source_directories: lib # a comma delimited list of directories in your project root that contains source to package.
